theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
signal_strength = true
ip = false
speed_up = false
graph_up = false
interval = 5
use_bits = false

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %R"
