#!/usr/bin/env bash

code --install-extension GregorBiswanger.json2ts
code --install-extension aaronthomas.vscode-snazzy-operator
code --install-extension abusaidm.html-snippets
code --install-extension alefragnani.Bookmarks
code --install-extension alireza94.theme-gotham
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension austin.code-gnu-global
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension crisward.riot-tag
code --install-extension Dart-Code.dart-code
code --install-extension dbaeumer.vscode-eslint
code --install-extension dcasella.monokai-plusplus
code --install-extension dracula-theme.theme-dracula
code --install-extension dzannotti.vscode-babel-coloring
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension Equinusocio.vsc-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension file-icons.file-icons
code --install-extension flowtype.flow-for-vscode
code --install-extension formulahendry.terminal
code --install-extension gcazaciuc.vscode-flow-ide
code --install-extension gerane.Theme-Afterglow
code --install-extension gerane.Theme-ArtSchool
code --install-extension gerane.Theme-azure
code --install-extension gerane.Theme-Batman
code --install-extension gerane.Theme-FlatlandMonokai
code --install-extension glennsl.vscode-duotone-dark-faithful
code --install-extension hnw.vscode-auto-open-markdown-preview
code --install-extension hoovercj.vscode-power-mode
code --install-extension jasonnutter.search-node-modules
code --install-extension josef.rouge-theme
code --install-extension kyleerickson.night-rider
code --install-extension lextudio.restructuredtext
code --install-extension liuji-jim.vue
code --install-extension loiane.ts-extension-pack
code --install-extension marcostazi.VS-code-vagrantfile
code --install-extension marvinhagemeister.theme-afterglow-remastered
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.Theme-1337
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension nonylene.dark-molokai-theme
code --install-extension octref.vetur
code --install-extension PKief.material-icon-theme
code --install-extension pmneo.tsimporter
code --install-extension primalmotion.primal
code --install-extension raashida.fixthecode-vs
code --install-extension rbbit.typescript-hero
code --install-extension redhat.java
code --install-extension ryu1kn.text-marker
code --install-extension sdras.night-owl
code --install-extension stringham.move-ts
code --install-extension teabyii.ayu
code --install-extension twxs.cmake
code --install-extension ulthes.theme-firewatch
code --install-extension vector-of-bool.cmake-tools
code --install-extension waderyan.nodejs-extension-pack
code --install-extension wayou.vscode-todo-highlight
code --install-extension webreflection.literally-html
code --install-extension wesbos.theme-cobalt2
code --install-extension wholroyd.jinja
code --install-extension xabikos.JavaScriptSnippets
code --install-extension zhuangtongfa.Material-theme
