#!/usr/bin/env bash

code --install-extension ms-python.python
code --install-extension redhat.java
code --install-extension EditorConfig.EditorConfig
code --install-extension abusaidm.html-snippets
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension crisward.riot-tag
code --install-extension dbaeumer.vscode-eslint
code --install-extension dzannotti.vscode-babel-coloring
code --install-extension eg2.vscode-npm-script
code --install-extension PKief.material-icon-theme
code --install-extension formulahendry.terminal
code --install-extension hnw.vscode-auto-open-markdown-preview
code --install-extension jasonnutter.search-node-modules
code --install-extension liuji-jim.vue
code --install-extension marcostazi.VS-code-vagrantfile
code --install-extension octref.vetur
code --install-extension waderyan.nodejs-extension-pack
code --install-extension xabikos.JavaScriptSnippets
code --install-extension zhuangtongfa.Material-theme
code --install-extension dracula-theme.theme-dracula
code --install-extension Equinusocio.vsc-material-theme
code --install-extension alireza94.theme-gotham
code --install-extension raashida.fixthecode-vs
code --install-extension lextudio.restructuredtext
code --install-extension loiane.ts-extension-pack
code --install-extension eamodio.gitlens
code --install-extension formulahendry.auto-close-tag
code --install-extension wayou.vscode-todo-highlight
code --install-extension yahya-gilany.vscode-pomodoro
code --install-extensions primalmotion.primal
code --install-extension ulthes.theme-firewatch
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension teabyii.ayu
code --install-extension nonylene.dark-molokai-theme
code --install-extension ms-vscode.theme-1337
code --install-extension ryu1kn.text-marker
code --install-extension webreflection.literally-html
code --install-extesion alefragnani.bookmarks
code --install-extension dart-code.dart-code
code --install-extension sbrink.elm
code --install-extension twxs.cmake
code --install-extension vector-of-bool.cmake-tools
code --install-extension slb235.vscode-coffeelint
code --install-extension orta.vscode-jest
code --install-extension ms-vscode.cpptools
code --install-extension austin.code-gnu-global
code --install-extension RobbOwen.synthwave-vscode
code --install-extension be5invis.vscode-custom-css
